// ─── Circle body text ─────────────────────────────────────────────────────────
// Expanded essay blending the user's paragraph with the side dialogue themes.
// Long enough to fill a ~600px circle at 11px monospace.
export const CIRCLE_TEXT = `Latimer Design presents 余白 (Yohaku): An exploration of negative space in digital typography. 2026. Mixed media. The white page is not empty. It is already full of meaning — the absence is what gives the mark its power. In Japanese aesthetics, what is left unsaid carries more weight than what is spoken. — Kenya Hara, White, 2007. 文字のない空間は、文字と同じくらい慎重にデザインされなければならない。 The space where there are no characters must be designed as carefully as the characters themselves. — Helmut Schmid, Typography Today, 1980. Typography is the discipline of arranging type so that language becomes visible. It is not decoration. It is not style. It is the architecture of thought made legible. Every decision — the weight of a stroke, the space between lines, the silence at the margin — is a decision about meaning. 余白は沈黙ではない。余白は呼吸である。存在と不在の間にある緊張のことだ。 The best decisions are the ones nobody notices. The page remembers everything you left out. Somebody picked up and it was just silence. The line went dead around 3 in the morning. Still there? います。 The mark and the space. Both. 両方。 It is the space between the notes — that is where the music lives. What Hara said — the absence is the design. You do not hear it until it stops. Language becomes visible. It is not decoration. It is not style. It is the weight of a stroke. The space between lines. The silence at the margin. 間。 Ma. The pause. Do you hear it? わかる？ Yeah. The silence carries weight. Not nothing. Breath. そう。 The space between the notes — that is where the music lives. 余白。 Right. 見えない。 That is the point. Every decision is a decision about meaning. 活字は思考の建築である。`;

// ─── Side dialogue ─────────────────────────────────────────────────────────────
export const LEFT_DIALOGUE: string[] = [
  '[ピー、ピー、ピー]',
  'もしもし。',
  'YEAH.',
  'I SEE IT.',
  '見える？',
  'THE SPACE.',
  'BETWEEN.',
  'うん。',
  '[STATIC]',
  '間。',
  'MA.',
  'THE PAUSE.',
  'DO YOU HEAR IT?',
  'わかる？',
  'YEAH YEAH.',
  'THE SILENCE.',
  '— IT CARRIES WEIGHT',
  'THE LINE WENT DEAD AROUND 3 IN THE MORNING.',
  '[DIAL TONE]',
  'WAIT.',
  'まだいる？',
  "I'M HERE.",
  'OKAY.',
  'うん、うん。',
  '[PAPER]',
  'NOT NOTHING.',
  '余白。',
  'RIGHT.',
  'BREATH.',
  'そう。',
  "YOU DON'T HEAR IT UNTIL IT STOPS.",
  '[CLICK]',
  'HELLO?',
  'まだいる。',
  'GOOD.',
  'I SEE.',
  '見えた。',
  '[BEEP]',
  'OKAY.',
  'うん。',
  '— THE MARK.',
  'AND THE SPACE.',
  'BOTH.',
  '両方。',
  'SOMEBODY PICKED UP AND IT WAS JUST SILENCE.',
  '[LONG PAUSE]',
  'STILL THERE?',
  'います。',
  'GOOD.',
  'TYPOGRAPHY.',
  'タイポグラフィ。',
  'YEAH.',
  'INVISIBLE.',
  '見えない。',
  "THAT'S THE POINT.",
  'そう。',
  "IT'S THE SPACE BETWEEN THE NOTES — THAT'S WHERE THE MUSIC LIVES.",
  '[CLICK]',
  'HELLO?',
  'GONE.',
  '[ピー]',
  'OKAY.',
  'I SEE.',
  'わかった。',
  '[END]',
  '...',
  '[ピー、ピー]',
  'もしもし。',
  'AGAIN.',
  'また。',
  'THE SPACE.',
  'STILL THERE.',
  'うん。',
  '[STATIC]',
  'BREATH.',
  'BREATH.',
  '呼吸。',
  'RIGHT.',
  'そう。',
  'WHAT HARA SAID — THE ABSENCE IS THE DESIGN.',
  '[DIAL TONE]',
  'WAIT.',
  'まだ。',
  'OKAY.',
  'うん。',
  '[END]',
  '...',
  'THE WEIGHT OF A STROKE.',
  'THE SPACE BETWEEN LINES.',
  'THE SILENCE AT THE MARGIN.',
  'うん、うん。',
  '[STATIC]',
  'BREATH.',
  'そう。',
  '[END]',
];

export const RIGHT_DIALOGUE: string[] = [
  '[SOMEBODY PICKS UP]',
  'HELLO?',
  '...NEGATIVE SPACE...',
  '[MUFFLED]',
  'WHAT HARA SAID —',
  'THE ABSENCE.',
  "I'M LISTENING.",
  'はい。',
  'YES.',
  '[RUSTLING]',
  "IT'S NOT NOTHING.",
  "IT'S BREATH.",
  '余白。',
  'RIGHT.',
  'わかった。',
  'THE MARK.',
  'AND THE SPACE.',
  'BOTH.',
  '両方。',
  'THE BEST DECISIONS ARE THE ONES NOBODY NOTICES.',
  '[LONG PAUSE]',
  'STILL THERE?',
  'います。',
  'GOOD.',
  'TYPOGRAPHY.',
  'タイポグラフィ。',
  'YEAH.',
  'INVISIBLE.',
  '見えない。',
  "THAT'S THE POINT.",
  'そう。',
  'EVERY DECISION IS A DECISION ABOUT MEANING.',
  '[CLICK]',
  'HELLO?',
  'GONE.',
  '[ピー]',
  'OKAY.',
  'I SEE.',
  'わかった。',
  '[END]',
  '...',
  '[SOMEBODY PICKS UP]',
  'HELLO?',
  'AGAIN.',
  'また。',
  'THE ABSENCE.',
  'YES.',
  'はい。',
  '[RUSTLING]',
  "IT'S BREATH.",
  '余白。',
  'RIGHT.',
  'わかった。',
  'THE MARK.',
  'BOTH.',
  '両方。',
  'THE PAGE REMEMBERS EVERYTHING YOU LEFT OUT.',
  '[PAUSE]',
  'STILL THERE?',
  'います。',
  'GOOD.',
  'INVISIBLE.',
  '見えない。',
  "THAT'S IT.",
  'そう。',
  '[CLICK]',
  'GONE.',
  '[ピー]',
  'OKAY.',
  'わかった。',
  '[END]',
  '...',
  'LANGUAGE BECOMES VISIBLE.',
  'IT IS NOT DECORATION.',
  'IT IS NOT STYLE.',
  'はい。',
  '[STATIC]',
  'BREATH.',
  'そう。',
  '[END]',
  '...',
];
